#!/usr/bin/env bash

# Abort if we run into an unexpected error.
# Without this, we may make changes to a state we aren't expecting.
set -e

# Arguments
#   - $1: The argument name
#   - $2: The argument pattern
#   - $3: The argument value
function arg() {
    case $2 in
        uint)
            if [[ $3 =~ ^[0-9]+$ ]]
            then
                return
            fi
            ;;
        *)
            echo "internal error: unknown pattern <$2>"
            exit 1
            ;;
    esac

    echo "argument <$1>: \"$3\" does not match pattern $2"
    exit 1
}

source modules/cmd.sh
source modules/squash.sh

case $1 in
    help)
        cmd_help
        ;;
    squash)
        shift
        cmd_squash $@
        ;;
    "")
        cmd_none
        ;;
    *)
        cmd_unknown $1
        exit 1
        ;;
esac
