#!/usr/bin/env bash

# Abort if we run into an unexpected error.
# Without this, we may make changes to a state we aren't expecting.
set -e

# Arguments
#   - $1: The argument name
#   - $2: The argument pattern
#   - $3: The argument value
function validate() {
    case $2 in
        uint)
            if [[ $3 =~ ^[0-9]+$ ]]
            then
                return
            fi
            ;;
        *)
            echo "internal error: unknown pattern <$2>"
            exit 1
            ;;
    esac

    echo "error: argument <$1> with value \"$3\" does not match pattern $2"
    exit 1
}

MODULES_DIR=$(dirname $0)/modules
source $MODULES_DIR/cmd.sh
source $MODULES_DIR/squash.sh
source $MODULES_DIR/sync.sh

case $1 in
    help)
        cmd_help
        ;;
    squash)
        shift
        cmd_squash $@
        ;;
    sync)
        shift
        cmd_sync $@
        ;;
    "")
        cmd_none
        ;;
    *)
        cmd_unknown $1
        exit 1
        ;;
esac
